name: Auto approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: hmarr/auto-approve-action@134e1011866211ab5b452c8ab06ea0447e888610
        with:
          github-token: ${{secrets.GH_TOKEN}}
